### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [TranNgocKhoa/CSSubmit#1]
How much does JOSEPH DRISCOLL make (including benefits)?

The employee name should be Joseph, not JOSEPH DRISCOLL ;)

**Comment by tuanhung303** [comment]
try to get some example about group by function in pandas/dataframe. It can help you to resolve most of questions

**Comment by coderschoolreview** [comment]
Hi, 
Is there a Google Data Studio link? I can not find it.

**Comment by TranNgocKhoa** [comment]
> Hi,
> Is there a Google Data Studio link? I can not find it.

I'm so sorry, I thought only Python Notebook with Dashboard is ok.
Here is my update. Please forget me about disturbing you in weekend
https://datastudio.google.com/reporting/e569ff3c-692d-4e4e-b61b-0d29fdfaed74

It will be ok if I'm gotten punished for this
